# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

name: Node.js Package

on:
  push:
    branches:
      - main  # Adjust this to your main branch name (e.g., "main", "master")
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run Mocha Tests
        id: mocha
        run: |
          npx mocha --reporter spec || true  # Show detailed output first
          npx mocha --reporter json > test-results.json
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: mocha-test-results
          path: test-results.json
      - name: Display Test Results
        run: cat test-results.json || echo "No test results available"
      - name: Score Test Results
        run: |
          # Calculate the score based on the test results
          TEST_RESULTS=$(cat test-results.json)
          TOTAL_TESTS=$(echo $TEST_RESULTS | jq '.stats.tests')
          PASSED_TESTS=$(echo $TEST_RESULTS | jq '.stats.passes')
          SCORE=$(echo "scale=2; ($PASSED_TESTS / $TOTAL_TESTS) * 100" | bc)

          echo "Total Tests: $TOTAL_TESTS"
          echo "Passed Tests: $PASSED_TESTS"
          echo "Score: $SCORE%"

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
